#!/usr/bin/env python3
"""Regenerates assets/ for the architecture dossier from its real sources.

Run from this directory: python3 prepare_assets.py

What's reproducible from files already in this repo:
  - fig-scenetree.png / fig-uml.png  <- rendered here from diagrams/*.dot
    (Graphviz; `dot` must be on PATH)
  - fig-goal.png                     <- copied straight from the game's own
    help illustration (assets/graphics/help/goal.png) — shows every field
    hazard with its real score value, drawn with the same shapes/colors as
    their in-game _draw() sprites.
  - centipede-icon.png               <- rendered here from centipede-icon.svg
    (a small dossier-only title-block icon: this project's real icon.svg is
    still a placeholder, see the project CLAUDE.md's "Bekannte offene
    Punkte" — needs `inkscape` on PATH)

What ISN'T reproducible by this script (kept only as the already-captured
file already sitting in assets/ — this script leaves it alone):
  - fig-gameplay.png — a real screenshot captured live via godot-mcp-pro
    during the 2026-09-18 session (a wave in progress, mushroom field +
    centipede visible). Recapturing it needs a live editor session with the
    MCP addon; there's nothing to "run" here.
"""

import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROJECT_ROOT = HERE.parent.parent
ASSETS = HERE / "assets"
DIAGRAMS = HERE / "diagrams"

ASSETS.mkdir(exist_ok=True)


def render_diagram(dot_file: Path, out_file: Path, dpi: int = 150) -> None:
    subprocess.run(
        ["dot", "-Tpng", f"-Gdpi={dpi}", str(dot_file), "-o", str(out_file)],
        check=True,
    )
    print("rendered", out_file.relative_to(HERE))


def render_svg(svg_file: Path, out_file: Path, width: int = 128) -> None:
    subprocess.run(
        [
            "inkscape", str(svg_file),
            "--export-type=png",
            f"--export-filename={out_file}",
            f"--export-width={width}",
        ],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    print("rendered", out_file.relative_to(HERE))


def copy_asset(src: Path, dst: Path) -> None:
    dst.write_bytes(src.read_bytes())
    print("copied", dst.relative_to(HERE), "<-", src)


def main() -> None:
    render_diagram(DIAGRAMS / "scenetree.dot", ASSETS / "fig-scenetree.png")
    render_diagram(DIAGRAMS / "uml.dot", ASSETS / "fig-uml.png")
    render_svg(ASSETS / "centipede-icon.svg", ASSETS / "centipede-icon.png")

    copy_asset(
        PROJECT_ROOT / "assets" / "graphics" / "help" / "goal.png",
        ASSETS / "fig-goal.png",
    )

    print(
        "\nfig-gameplay.png left untouched — a real editor screenshot, not "
        "regenerated by this script (see the module docstring)."
    )


if __name__ == "__main__":
    main()
